"""tasks

Revision ID: 063225e2be35
Revises: b75ed2f1ded4
Create Date: 2026-10-05 14:44:42.775121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401 — UTCDateTime и другие свои типы


# revision identifiers, used by Alembic.
revision: str = '063225e2be35'
down_revision: Union[str, Sequence[str], None] = 'b75ed2f1ded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('deadline', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('done_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['employee.id'], name=op.f('fk_task_assignee_id_employee')),
    sa.ForeignKeyConstraint(['author_id'], ['employee.id'], name=op.f('fk_task_author_id_employee')),
    sa.ForeignKeyConstraint(['done_by_id'], ['employee.id'], name=op.f('fk_task_done_by_id_employee')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_task_location_id_location')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_task_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_order_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignee_id'))

    op.drop_table('task')
    # ### end Alembic commands ###
