"""notifications and tracking

Revision ID: 1ed55ae52dd7
Revises: 62d0ee885fd9
Create Date: 2026-10-08 22:30:40.303990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401 — UTCDateTime и другие свои типы


# revision identifiers, used by Alembic.
revision: str = '1ed55ae52dd7'
down_revision: Union[str, Sequence[str], None] = '62d0ee885fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], name=op.f('fk_notification_template_status_id_order_status'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_template')),
    sa.UniqueConstraint('status_id', name=op.f('uq_notification_template_status_id'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('counteragent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counteragent_id'], ['counteragent.id'], name=op.f('fk_notification_counteragent_id_counteragent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['employee.id'], name=op.f('fk_notification_created_by_id_employee')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_notification_order_id_order'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_state'), ['state'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_hours', sa.String(length=100), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_tracking_code'), ['tracking_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_code'))
        batch_op.drop_column('tracking_code')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('work_hours')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_state'))
        batch_op.drop_index(batch_op.f('ix_notification_order_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    op.drop_table('notification_template')
    # ### end Alembic commands ###
