"""boards

Revision ID: 62d0ee885fd9
Revises: 063225e2be35
Create Date: 2026-10-05 16:56:45.633101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401 — UTCDateTime и другие свои типы


# revision identifiers, used by Alembic.
revision: str = '62d0ee885fd9'
down_revision: Union[str, Sequence[str], None] = '063225e2be35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_board_space_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_space'))
    )
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['board_space.id'], name=op.f('fk_board_space_id_board_space'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board'))
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_space_id'), ['space_id'], unique=False)

    op.create_table('board_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_board_column_board_id_board'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_column'))
    )
    with op.batch_alter_table('board_column', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_column_board_id'), ['board_id'], unique=False)

    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('deadline', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['employee.id'], name=op.f('fk_card_assignee_id_employee')),
    sa.ForeignKeyConstraint(['author_id'], ['employee.id'], name=op.f('fk_card_author_id_employee')),
    sa.ForeignKeyConstraint(['column_id'], ['board_column.id'], name=op.f('fk_card_column_id_board_column'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_card_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_column_id'), ['column_id'], unique=False)

    op.create_table('card_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['employee.id'], name=op.f('fk_card_comment_author_id_employee')),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_comment_card_id_card'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_comment'))
    )
    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_comment_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_comment_card_id'))

    op.drop_table('card_comment')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_column_id'))

    op.drop_table('card')
    with op.batch_alter_table('board_column', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_column_board_id'))

    op.drop_table('board_column')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_space_id'))

    op.drop_table('board')
    op.drop_table('board_space')
    # ### end Alembic commands ###
