"""settings, quick orders, checklist

Revision ID: af23e4dc3ef3
Revises: 7c2f1a9d4e10
Create Date: 2026-10-11 00:19:40.389264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401 — UTCDateTime и другие свои типы


# revision identifiers, used by Alembic.
revision: str = 'af23e4dc3ef3'
down_revision: Union[str, Sequence[str], None] = '7c2f1a9d4e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    op.create_table('quick_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=False),
    sa.Column('approximate_price', sa.String(length=100), nullable=True),
    sa.Column('works', sa.JSON(), nullable=False),
    sa.Column('parts_note', sa.String(length=300), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_order'))
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('check_out', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    op.drop_table('quick_order')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
