"""initial schema

Revision ID: b75ed2f1ded4
Revises: 
Create Date: 2026-10-05 11:52:49.610158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401 — UTCDateTime и другие свои типы


# revision identifiers, used by Alembic.
revision: str = 'b75ed2f1ded4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('affects_balance', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_item'))
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('order_number_prefix', sa.String(length=10), nullable=False),
    sa.Column('next_order_number', sa.Integer(), nullable=False),
    sa.Column('next_sale_number', sa.Integer(), nullable=False),
    sa.Column('date_lock', sa.String(length=10), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    op.create_table('complete_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complete_set'))
    )
    op.create_table('counteragent_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counteragent_type'))
    )
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary_percent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_fixed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_type'))
    )
    op.create_table('how_know',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_how_know'))
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phones', sa.String(length=300), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('is_float', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measure'))
    )
    op.create_table('nomenclature_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('salary_percent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_fixed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nomenclature_group.id'], name=op.f('fk_nomenclature_group_parent_id_nomenclature_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclature_group'))
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('pay_required', sa.Boolean(), nullable=False),
    sa.Column('comment_mode', sa.String(length=10), nullable=False),
    sa.Column('role_access', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status'))
    )
    op.create_table('order_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_type'))
    )
    op.create_table('price_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_minimal', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_type'))
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('home_page', sa.String(length=30), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], name=op.f('fk_brand_device_type_id_device_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand'))
    )
    op.create_table('cash_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('accepts_cash', sa.Boolean(), nullable=False),
    sa.Column('accepts_bank', sa.Boolean(), nullable=False),
    sa.Column('bank_percent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allow_negative', sa.Boolean(), nullable=False),
    sa.Column('allow_internal_move', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bank_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_cash_register_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_register'))
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phones', sa.String(length=300), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_employee_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee')),
    sa.UniqueConstraint('email', name=op.f('uq_employee_email'))
    )
    op.create_table('form_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_type_id', sa.Integer(), nullable=True),
    sa.Column('counteragent_type_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=10), nullable=False),
    sa.Column('place', sa.String(length=10), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_only_dictionary', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['counteragent_type_id'], ['counteragent_type.id'], name=op.f('fk_form_field_counteragent_type_id_counteragent_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_type.id'], name=op.f('fk_form_field_order_type_id_order_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_field'))
    )
    op.create_table('nomenclature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_work', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('guarantee_days', sa.Integer(), nullable=False),
    sa.Column('min_count', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('has_serials', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('salary_percent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_fixed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['nomenclature_group.id'], name=op.f('fk_nomenclature_group_id_nomenclature_group')),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], name=op.f('fk_nomenclature_measure_id_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclature')),
    sa.UniqueConstraint('code', name=op.f('uq_nomenclature_code'))
    )
    op.create_index(op.f('ix_nomenclature_article'), 'nomenclature', ['article'], unique=False)
    op.create_index(op.f('ix_nomenclature_name'), 'nomenclature', ['name'], unique=False)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_store_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store'))
    )
    op.create_table('counteragent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('phones', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('max_messenger', sa.String(length=100), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('how_know_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_buyer', sa.Boolean(), nullable=False),
    sa.Column('is_vendor', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('allow_sms', sa.Boolean(), nullable=False),
    sa.Column('allow_email', sa.Boolean(), nullable=False),
    sa.Column('allow_telegram', sa.Boolean(), nullable=False),
    sa.Column('allow_max', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['how_know_id'], ['how_know.id'], name=op.f('fk_counteragent_how_know_id_how_know')),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], name=op.f('fk_counteragent_manager_id_employee')),
    sa.ForeignKeyConstraint(['type_id'], ['counteragent_type.id'], name=op.f('fk_counteragent_type_id_counteragent_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counteragent'))
    )
    op.create_index(op.f('ix_counteragent_name'), 'counteragent', ['name'], unique=False)
    op.create_index(op.f('ix_counteragent_phones'), 'counteragent', ['phones'], unique=False)
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_device_model_brand_id_brand')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_model'))
    )
    op.create_table('employee_location',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_employee_location_employee_id_employee'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_employee_location_location_id_location'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'location_id', name=op.f('pk_employee_location'))
    )
    op.create_table('nomenclature_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('price_type_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_nomenclature_price_location_id_location')),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], name=op.f('fk_nomenclature_price_nomenclature_id_nomenclature'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_type_id'], ['price_type.id'], name=op.f('fk_nomenclature_price_price_type_id_price_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclature_price')),
    sa.UniqueConstraint('nomenclature_id', 'price_type_id', 'location_id', name=op.f('uq_nomenclature_price_nomenclature_id'))
    )
    op.create_table('salary_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_type_id', sa.Integer(), nullable=True),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('accrue_on', sa.String(length=10), nullable=False),
    sa.Column('discount_by', sa.String(length=10), nullable=False),
    sa.Column('subtract_negative_margin', sa.Boolean(), nullable=False),
    sa.Column('keep_on_return', sa.Boolean(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_salary_rule_employee_id_employee'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_salary_rule_location_id_location')),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_type.id'], name=op.f('fk_salary_rule_order_type_id_order_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_rule'))
    )
    op.create_index(op.f('ix_salary_rule_employee_id'), 'salary_rule', ['employee_id'], unique=False)
    op.create_table('stock_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], name=op.f('fk_stock_balance_nomenclature_id_nomenclature')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_stock_balance_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_balance')),
    sa.UniqueConstraint('store_id', 'nomenclature_id', name=op.f('uq_stock_balance_store_id'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('order_type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('counteragent_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=False),
    sa.Column('complete_set', sa.JSON(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('device_password', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('approximate_price', sa.String(length=100), nullable=True),
    sa.Column('has_prepayment', sa.Boolean(), nullable=False),
    sa.Column('deadline', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('how_know_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_purchase', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_action_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['employee.id'], name=op.f('fk_order_closed_by_id_employee')),
    sa.ForeignKeyConstraint(['counteragent_id'], ['counteragent.id'], name=op.f('fk_order_counteragent_id_counteragent')),
    sa.ForeignKeyConstraint(['created_by_id'], ['employee.id'], name=op.f('fk_order_created_by_id_employee')),
    sa.ForeignKeyConstraint(['how_know_id'], ['how_know.id'], name=op.f('fk_order_how_know_id_how_know')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_order_location_id_location')),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], name=op.f('fk_order_manager_id_employee')),
    sa.ForeignKeyConstraint(['master_id'], ['employee.id'], name=op.f('fk_order_master_id_employee')),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_type.id'], name=op.f('fk_order_order_type_id_order_type')),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], name=op.f('fk_order_status_id_order_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_index(op.f('ix_order_counteragent_id'), 'order', ['counteragent_id'], unique=False)
    op.create_index(op.f('ix_order_location_id'), 'order', ['location_id'], unique=False)
    op.create_index(op.f('ix_order_number'), 'order', ['number'], unique=True)
    op.create_index(op.f('ix_order_serial'), 'order', ['serial'], unique=False)
    op.create_index(op.f('ix_order_status_id'), 'order', ['status_id'], unique=False)
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('date', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('counteragent_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_purchase', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counteragent_id'], ['counteragent.id'], name=op.f('fk_sale_counteragent_id_counteragent')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_sale_location_id_location')),
    sa.ForeignKeyConstraint(['seller_id'], ['employee.id'], name=op.f('fk_sale_seller_id_employee')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_sale_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale')),
    sa.UniqueConstraint('number', name=op.f('uq_sale_number'))
    )
    op.create_index(op.f('ix_sale_date'), 'sale', ['date'], unique=False)
    op.create_index(op.f('ix_sale_location_id'), 'sale', ['location_id'], unique=False)
    op.create_table('order_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_order_file_employee_id_employee')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_file_order_id_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_file'))
    )
    op.create_index(op.f('ix_order_file_order_id'), 'order_file', ['order_id'], unique=False)
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_order_history_employee_id_employee')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_history_order_id_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], name=op.f('fk_order_history_status_id_order_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_history'))
    )
    op.create_index(op.f('ix_order_history_order_id'), 'order_history', ['order_id'], unique=False)
    op.create_table('order_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=True),
    sa.Column('is_work', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sold_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('guarantee_days', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], name=op.f('fk_order_position_nomenclature_id_nomenclature')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_position_order_id_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performer_id'], ['employee.id'], name=op.f('fk_order_position_performer_id_employee')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_order_position_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_position'))
    )
    op.create_index(op.f('ix_order_position_order_id'), 'order_position', ['order_id'], unique=False)
    op.create_table('sale_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=True),
    sa.Column('is_work', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sold_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('guarantee_days', sa.Integer(), nullable=False),
    sa.Column('serials', sa.JSON(), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], name=op.f('fk_sale_position_nomenclature_id_nomenclature')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_sale_position_sale_id_sale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_position'))
    )
    op.create_index(op.f('ix_sale_position_sale_id'), 'sale_position', ['sale_id'], unique=False)
    op.create_table('stock_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('date', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=True),
    sa.Column('counteragent_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('ext_number', sa.String(length=50), nullable=True),
    sa.Column('ext_date', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counteragent_id'], ['counteragent.id'], name=op.f('fk_stock_document_counteragent_id_counteragent')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_stock_document_location_id_location')),
    sa.ForeignKeyConstraint(['responsible_id'], ['employee.id'], name=op.f('fk_stock_document_responsible_id_employee')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_stock_document_sale_id_sale')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_stock_document_store_id_store')),
    sa.ForeignKeyConstraint(['to_store_id'], ['store.id'], name=op.f('fk_stock_document_to_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_document'))
    )
    op.create_index(op.f('ix_stock_document_date'), 'stock_document', ['date'], unique=False)
    op.create_index(op.f('ix_stock_document_type'), 'stock_document', ['type'], unique=False)
    op.create_table('salary_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('date', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_position_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['employee.id'], name=op.f('fk_salary_event_created_by_id_employee')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_salary_event_employee_id_employee')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_salary_event_location_id_location')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_salary_event_order_id_order')),
    sa.ForeignKeyConstraint(['order_position_id'], ['order_position.id'], name=op.f('fk_salary_event_order_position_id_order_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['salary_rule.id'], name=op.f('fk_salary_event_rule_id_salary_rule'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_salary_event_sale_id_sale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_event'))
    )
    op.create_index(op.f('ix_salary_event_date'), 'salary_event', ['date'], unique=False)
    op.create_index(op.f('ix_salary_event_employee_id'), 'salary_event', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_event_order_id'), 'salary_event', ['order_id'], unique=False)
    op.create_table('stock_document_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_accounted', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('serials', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['stock_document.id'], name=op.f('fk_stock_document_position_document_id_stock_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], name=op.f('fk_stock_document_position_nomenclature_id_nomenclature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_document_position'))
    )
    op.create_index(op.f('ix_stock_document_position_document_id'), 'stock_document_position', ['document_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('cash_item_id', sa.Integer(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_bank', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('counteragent_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('stock_document_id', sa.Integer(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cash_item_id'], ['cash_item.id'], name=op.f('fk_transaction_cash_item_id_cash_item')),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_register.id'], name=op.f('fk_transaction_cash_register_id_cash_register')),
    sa.ForeignKeyConstraint(['counteragent_id'], ['counteragent.id'], name=op.f('fk_transaction_counteragent_id_counteragent')),
    sa.ForeignKeyConstraint(['created_by_id'], ['employee.id'], name=op.f('fk_transaction_created_by_id_employee')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_transaction_employee_id_employee')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_transaction_location_id_location')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_transaction_order_id_order')),
    sa.ForeignKeyConstraint(['pair_id'], ['transaction.id'], name=op.f('fk_transaction_pair_id_transaction')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_transaction_sale_id_sale')),
    sa.ForeignKeyConstraint(['stock_document_id'], ['stock_document.id'], name=op.f('fk_transaction_stock_document_id_stock_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_index(op.f('ix_transaction_cash_register_id'), 'transaction', ['cash_register_id'], unique=False)
    op.create_index(op.f('ix_transaction_counteragent_id'), 'transaction', ['counteragent_id'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_order_id'), 'transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_transaction_sale_id'), 'transaction', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_sale_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_order_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_counteragent_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_cash_register_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_stock_document_position_document_id'), table_name='stock_document_position')
    op.drop_table('stock_document_position')
    op.drop_index(op.f('ix_salary_event_order_id'), table_name='salary_event')
    op.drop_index(op.f('ix_salary_event_employee_id'), table_name='salary_event')
    op.drop_index(op.f('ix_salary_event_date'), table_name='salary_event')
    op.drop_table('salary_event')
    op.drop_index(op.f('ix_stock_document_type'), table_name='stock_document')
    op.drop_index(op.f('ix_stock_document_date'), table_name='stock_document')
    op.drop_table('stock_document')
    op.drop_index(op.f('ix_sale_position_sale_id'), table_name='sale_position')
    op.drop_table('sale_position')
    op.drop_index(op.f('ix_order_position_order_id'), table_name='order_position')
    op.drop_table('order_position')
    op.drop_index(op.f('ix_order_history_order_id'), table_name='order_history')
    op.drop_table('order_history')
    op.drop_index(op.f('ix_order_file_order_id'), table_name='order_file')
    op.drop_table('order_file')
    op.drop_index(op.f('ix_sale_location_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_date'), table_name='sale')
    op.drop_table('sale')
    op.drop_index(op.f('ix_order_status_id'), table_name='order')
    op.drop_index(op.f('ix_order_serial'), table_name='order')
    op.drop_index(op.f('ix_order_number'), table_name='order')
    op.drop_index(op.f('ix_order_location_id'), table_name='order')
    op.drop_index(op.f('ix_order_counteragent_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('stock_balance')
    op.drop_index(op.f('ix_salary_rule_employee_id'), table_name='salary_rule')
    op.drop_table('salary_rule')
    op.drop_table('nomenclature_price')
    op.drop_table('employee_location')
    op.drop_table('device_model')
    op.drop_index(op.f('ix_counteragent_phones'), table_name='counteragent')
    op.drop_index(op.f('ix_counteragent_name'), table_name='counteragent')
    op.drop_table('counteragent')
    op.drop_table('store')
    op.drop_index(op.f('ix_nomenclature_name'), table_name='nomenclature')
    op.drop_index(op.f('ix_nomenclature_article'), table_name='nomenclature')
    op.drop_table('nomenclature')
    op.drop_table('form_field')
    op.drop_table('employee')
    op.drop_table('cash_register')
    op.drop_table('brand')
    op.drop_table('role')
    op.drop_table('problem')
    op.drop_table('price_type')
    op.drop_table('order_type')
    op.drop_table('order_status')
    op.drop_table('nomenclature_group')
    op.drop_table('measure')
    op.drop_table('location')
    op.drop_table('how_know')
    op.drop_table('device_type')
    op.drop_table('counteragent_type')
    op.drop_table('complete_set')
    op.drop_table('company')
    op.drop_table('cash_item')
    # ### end Alembic commands ###
