"""Права доступа ролей — 1-в-1 как в LiveSklad.

PERMISSIONS: флажки (код → раздел, описание, родитель). Родитель должен быть включён,
чтобы дочернее право имело смысл (например, создание поступлений требует просмотра).
SCOPES: права-выборы (видимость «все / только свои / …»).
Проверка в API: app.api.deps.require("код").
"""

PERMISSIONS: dict[str, dict] = {
    "settingAccess": {"section": "Общие", "title": "Доступ к настройкам", "parent": None},
    "tariffAccess": {"section": "Общие", "title": "Доступ к подписке", "parent": None},
    "exportAccess": {"section": "Общие", "title": "Может экспортировать данные", "parent": None},
    "returnOrderProductAccess": {"section": "Общие", "title": "Может делать возвраты", "parent": None},
    "dictionarySalaryAccess": {"section": "Общие", "title": "Может задавать зарплату в справочниках", "parent": None},
    "counteragentSellerAccess": {"section": "Общие", "title": "Может видеть контрагентов поставщиков", "parent": None},
    "changeNotificationAccess": {"section": "Общие", "title": "Может редактировать текст уведомления", "parent": None},
    "isManagerAccess": {"section": "Общие", "title": "Показывать пользователя в списке менеджеров", "parent": None},
    "isMasterAccess": {"section": "Общие", "title": "Показывать пользователя в списке мастеров", "parent": None},
    "dashboardCustomerAccess": {"section": "Главная", "title": "Доступ ко всем пользователям", "parent": None},
    "dashboardFinanceAccess": {"section": "Главная", "title": "Доступ к разделу финансы", "parent": None},
    "dashboardOrderPeriodAccess": {"section": "Главная", "title": "Может просматривать статистику по заказам за период", "parent": None},
    "dashboardOrderClosedAccess": {"section": "Главная", "title": "Статистика по количеству \"Выданных\" заказов", "parent": None},
    "dashboardDeadlineAccess": {"section": "Главная", "title": "Карточка просроченных заказов", "parent": None},
    "dashboardHowKnowAccess": {"section": "Главная", "title": "Доступ к источникам рекламы", "parent": None},
    "dashboardCartAccess": {"section": "Главная", "title": "Карточка товаров в корзине", "parent": None},
    "createOrderAccess": {"section": "Заказы", "title": "Может принимать заказы", "parent": None},
    "deleteOrderAccess": {"section": "Заказы", "title": "Может удалять/восстанавливать заказы", "parent": None},
    "completeDeleteOrderAccess": {"section": "Заказы", "title": "Может удалять заказы полностью", "parent": "deleteOrderAccess"},
    "viewDeleteOrderAccess": {"section": "Заказы", "title": "Может видеть удаленные заказы", "parent": None},
    "counteragentOrderAccess": {"section": "Заказы", "title": "Может видеть заказчика", "parent": None},
    "orderPurchasePriceAccess": {"section": "Заказы", "title": "Может задавать себестоимость", "parent": None},
    "createOrderProductAccess": {"section": "Заказы", "title": "Может добавлять запчасти без привязки к работе", "parent": None},
    "giveOrderAccess": {"section": "Заказы", "title": "Может перемещать заказы", "parent": None},
    "changeOrderInfoAccess": {"section": "Заказы", "title": "Может редактировать информацию о заказе", "parent": None},
    "changeOrderPositionAccess": {"section": "Заказы", "title": "Может редактировать работы и материалы", "parent": None},
    "changeOrderMasterAccess": {"section": "Заказы", "title": "Может изменять мастера", "parent": None},
    "changeOrderManagerAccess": {"section": "Заказы", "title": "Может изменять менеджера", "parent": None},
    "deleteSaleDocumentAccess": {"section": "Продажи", "title": "Может удалять чеки", "parent": None},
    "counteragentShopAccess": {"section": "Продажи", "title": "Может видеть покупателя", "parent": None},
    "remainAccess": {"section": "Склад", "title": "Остатки", "parent": None},
    "purchaseAccess": {"section": "Склад", "title": "Поступления", "parent": None},
    "createPurchaseDocumentAccess": {"section": "Склад", "title": "Может создавать", "parent": "purchaseAccess"},
    "changePurchaseDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "purchaseAccess"},
    "deletePurchaseDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "purchaseAccess"},
    "moveAccess": {"section": "Склад", "title": "Перемещения", "parent": None},
    "createMoveDocumentAccess": {"section": "Склад", "title": "Может создавать", "parent": "moveAccess"},
    "changeMoveDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "moveAccess"},
    "deleteMoveDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "moveAccess"},
    "allStoreMoveAccess": {"section": "Склад", "title": "Может перемещать на недоступный склад", "parent": "moveAccess"},
    "saleReturnAccess": {"section": "Склад", "title": "Возвраты от клиентов", "parent": None},
    "changeSaleReturnDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "saleReturnAccess"},
    "deleteSaleReturnDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "saleReturnAccess"},
    "purchaseReturnAccess": {"section": "Склад", "title": "Возвраты поставщикам", "parent": None},
    "createPurchaseReturnDocumentAccess": {"section": "Склад", "title": "Может создавать", "parent": "purchaseReturnAccess"},
    "changePurchaseReturnDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "purchaseReturnAccess"},
    "deletePurchaseReturnDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "purchaseReturnAccess"},
    "inventoryAccess": {"section": "Склад", "title": "Инвентаризация", "parent": None},
    "createInventoryDocumentAccess": {"section": "Склад", "title": "Может создавать", "parent": "inventoryAccess"},
    "changeInventoryDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "inventoryAccess"},
    "deleteInventoryDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "inventoryAccess"},
    "cancellationAccess": {"section": "Склад", "title": "Списания", "parent": None},
    "createCancellationDocumentAccess": {"section": "Склад", "title": "Может создавать", "parent": "cancellationAccess"},
    "changeCancellationDocumentAccess": {"section": "Склад", "title": "Может изменять", "parent": "cancellationAccess"},
    "deleteCancellationDocumentAccess": {"section": "Склад", "title": "Может удалять", "parent": "cancellationAccess"},
    "storeSettingAccess": {"section": "Склад", "title": "Настройки склада", "parent": None},
    "createTaskAccess": {"section": "Задачи", "title": "Может ставить задачи", "parent": None},
    "changeAllTaskAccess": {"section": "Задачи", "title": "Может редактировать чужие задачи", "parent": None},
    "deleteAllTaskAccess": {"section": "Задачи", "title": "Может удалять чужие задачи", "parent": None},
    "shopSellerAccess": {"section": "Прайсы", "title": "Показывать прайсы поставщиков на вкладке \"Продажи\"", "parent": None},
    "sellerAccess": {"section": "Прайсы", "title": "Показывать вкладку \"Прайсы\"", "parent": None},
    "globalShopAccess": {"section": "Объявления", "title": "Показывать вкладку \"Обьявления\"", "parent": None},
    "createGlobalNomenclatureAccess": {"section": "Объявления", "title": "Может публиковать объявления", "parent": None},
    "changeCashRegisterAccess": {"section": "Финансы", "title": "Может создавать, изменять, удалять кассы", "parent": None},
    "moneyCashRegisterAccess": {"section": "Финансы", "title": "Может видеть деньги в кассе", "parent": None},
    "fiscalRegisterAccess": {"section": "Финансы", "title": "Онлайн кассы", "parent": None},
    "operationCashRegisterAccess": {"section": "Финансы", "title": "Доступны операции с деньгами", "parent": None},
    "salarySettingAccess": {"section": "Финансы", "title": "Настройки", "parent": None},
    "changeSalaryAccess": {"section": "Финансы", "title": "Может изменять начисления", "parent": None},
    "bonusPenaltyRevenueSalaryAccess": {"section": "Финансы", "title": "Может начислять бонусы/штрафы/премии", "parent": None},
    "cashSalaryAccess": {"section": "Финансы", "title": "Может выплачивать зарплату", "parent": None},
    "transactionAccess": {"section": "Финансы", "title": "Транзакции", "parent": None},
    "changeTransactionAccess": {"section": "Финансы", "title": "Может изменять транзакции", "parent": "transactionAccess"},
    "completeDeleteTransactionAccess": {"section": "Финансы", "title": "Может удалять транзакции полностью", "parent": "changeTransactionAccess"},
    "viewDeleteTransactionAccess": {"section": "Финансы", "title": "Может видеть удаленные транзакции", "parent": "transactionAccess"},
    "bookkeepingAccess": {"section": "Финансы", "title": "Денежный поток", "parent": None},
    "invoiceAccess": {"section": "Финансы", "title": "Счета", "parent": None},
    "allPriceAccess": {"section": "Финансы", "title": "Может видеть все цены, кроме закупочной", "parent": None},
    "purchasePriceAccess": {"section": "Финансы", "title": "Может видеть закупочный ценник", "parent": None},
    "marginPriceAccess": {"section": "Финансы", "title": "Может видеть валовую прибыль", "parent": "purchasePriceAccess"},
    "discountSaleAccess": {"section": "Финансы", "title": "Может делать скидку/наценку", "parent": None},
    "minPriceAccess": {"section": "Финансы", "title": "Может делать скидку ниже минимальной цены", "parent": None},
    "setPriceAccess": {"section": "Финансы", "title": "Может указать цену при отсутствии в справочнике", "parent": None},
    "changeCounteragentBalanceAccess": {"section": "Финансы", "title": "Может изменять баланс контрагента", "parent": None},
    "cashDateAccess": {"section": "Финансы", "title": "Может задавать дату транзакции", "parent": None},
    "reportAccess": {"section": "Аналитика", "title": "Отчеты", "parent": None},
    "statisticCallAccess": {"section": "Аналитика", "title": "Звонки", "parent": None},
    "notificationAccess": {"section": "Аналитика", "title": "Уведомления", "parent": None},
    "howKnowReportAccess": {"section": "Аналитика", "title": "Реклама", "parent": None},
    "howKnowAccess": {"section": "Аналитика", "title": "Источники рекламы", "parent": "howKnowReportAccess"},
    "storageFileAccess": {"section": "Хранилище", "title": "Показывать вкладку \"Хранилище\"", "parent": None},
    "deleteStorageFileAccess": {"section": "Хранилище", "title": "Может удалять файлы", "parent": "storageFileAccess"},
    "nomenclatureAccess": {"section": "Справочники", "title": "Товары", "parent": None},
    "workAccess": {"section": "Справочники", "title": "Работы", "parent": None},
    "counteragentAccess": {"section": "Справочники", "title": "Контрагенты", "parent": None},
    "brandModelDeviceAccess": {"section": "Справочники", "title": "Типы устройств, марки и модели", "parent": None},
    "completeSetAccess": {"section": "Справочники", "title": "Комплектация", "parent": None},
    "problemAccess": {"section": "Справочники", "title": "Неисправности", "parent": None},
    "cashItemAccess": {"section": "Справочники", "title": "Статьи движения денег", "parent": None},
    "measureAccess": {"section": "Справочники", "title": "Единицы измерения", "parent": None},
}

# Права-выборы. Значение хранится в Role.scopes[<ключ>] = <код варианта>.
SCOPES: dict[str, dict] = {
    "orders": {"title": "Заказы", "options": {"none": "Нет доступа", "all": "Все заказы", "own": "Только свои"}},
    "orderSalary": {
        "title": "Может задавать зарплату для работ/запчастей в заказе",
        "options": {"none": "Нет доступа", "own": "Только себе", "all": "Всем"},
    },
    "tasks": {"title": "Задачи", "options": {"none": "Нет доступа", "all": "Все задачи", "own": "Свои + назначенные"}},
    "cart": {"title": "Корзина", "options": {"none": "Нет доступа", "all": "Все корзины", "own": "Только своя"}},
    "salary": {
        "title": "Зарплата",
        "options": {"none": "Нет доступа", "all": "Все зарплаты", "own": "Только своя", "locations": "По локациям"},
    },
}

ALL_PERMISSION_CODES: list[str] = list(PERMISSIONS)
FULL_SCOPES: dict[str, str] = {"orders": "all", "orderSalary": "all", "tasks": "all", "cart": "all", "salary": "all"}
